Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Natan Lincoln Cruz Barbosa
// Data atual  : 11/12/2024
Var
 n1:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
n1<-10

		Repita
  	Escreval(n1)
  		n1<- n1 -1
		Ate n1<1

Fimalgoritmo